package com.example.android.flashcard.model;

public enum WordCategory {
    ACCESSORIES, ADVICE, AGREEMENT, AIRCRAFT, AMOUNT, ANIMALS, APPEARANCE, APPLIANCES, ARGUMENT, ART,
    BIOLOGY, BIRDS, BODY, BUILDINGS, BUSINESS, CARS, CAUSE, CERTAINTY, CHANGE, CHEMISTRY, CINEMA,
    CITY, CLOTHES, COLORS, COMMUNICATION, COMPUTERS, CONSTRUCTION, CONVERSATIONS, COOKING, CREATION,
    CRIME, CULTURE, DANGER, DECISIONS, DIFFICULTY, DISCUSSION, DOUBT, DRINKS, EATING, EDUCATION,
    EFFECT, ENGINEERING, ENVIRONMENT, FAILURE, FAMILY, FARMING, FEELINGS, FISH, FOOD, FRUIT,
    FURNITURE, GAMES, GARDENING, GEOGRAPHY, GUESSING, HEALTH, HISTORY, HOBBIES, HOLIDAY, HOUSES,
    HYGIENE, INSECTS, INTERNET, ISSUES, ITEMS, JEWELRY, JOBS, JUSTICE, LANGUAGE, LAW, LEISURE, LIFE,
    LITERATURE, LOGISTICS, MATERIALS, MATHEMATICS, MEDIA, MEDICINE, MILITARY, MONEY, MOVING, MUSIC,
    MYTHOLOGY, NATIONALITY, NEWS, NONE, NUMBERS, OBLIGATION, OPINION, PEOPLE, PERSONALITY, PHYSICS,
    PLACES, PLANTS, POLITICS, PREFERENCES, PUNISHMENT, QUALITIES, RAILWAY, RELATIONSHIP, RELIGION,
    ROUTINE, SCIENCE, SENSES, SHAPES, SHIPS, SHOPPING, SIZE, SOCIETY, SOUND, SPACE, SPECIAL, SPORTS,
    SUCCESS, SUGGESTIONS, TECHNOLOGY, THEATER, THOUGHTS, TIME, TRANSPORT, TRAVELLING, VEGETABLES,
    VISION, WAR, WEATHER, WORK, WRITING
}
